config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'
  get 'carts_controller/show'
  get 'carts_controller/new'
  #get 'cartitems/new'
  get 'top/main'
  resources :products
  
  root 'top#main'
  
  resources :cartitems, only: [:new, :create, :destroy]
  resources :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence:true
    validates :price, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
        def current_cart
            if session[:cart_id]
                cart = Cart.find(session[:cart_id])
            else
                cart = Cart.create
                session[:cart_id] = cart.id
            end
            cart
        end
        helper_method :current_cart
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @cartitem = Cartitem.new(product_id: params[:product_id])
  end
  
  def create
    cart = Cartitem.new(
      product_id: params[:cartitem][:product_id],
      cart_id: current_cart.id,
      qty: params[:cartitem][:qty])
    if cart.save
      flash[:success] = "saved"
      redirect_to root_path
    else
      flash.now[:danger] = "error"
      render '/cartitems/new'
    end
  end
  
  def destroy
    cartitem = Cartitem.find(params[:id])
    cartitem.destroy
    redirect_to root_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @product_id = current_cart.id
    @cartitems = Cartitem.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    if @product.save
      redirect_to root_path
    else
      render '/products/new'
    end
  end
  
  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to root_path
  end
  
  def show
    @product_id = current_cart.id
    @cartitems = Cartitem.all
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_controller_helper.rb
module CartsControllerHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<% if @cartitem.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @cartitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<% end %>




<%= form_for @cartitem, url: {action: :create} do |f| %>
    <p>
        商品名：<%= Product.find(@cartitem.product_id).name %>
    </p>
    <p>
        価格：<%= Product.find(@cartitem.product_id).price %>円
    </p>
    
    <p>
    <%= f.label :qty, '数量' %>
    <%= f.text_field :qty , :value =>"1" %>
    </p>
    
    <%= f.hidden_field :product_id %>
    <%= f.submit '登録' %>
<% end %>

app/views/carts/show.html.erb
<% price = 0 %>
<% @cartitems.each do |e| %>
    <br>
    <p>
        商品名：
        <%= Product.find(e.product_id).name %>
        個数：
        <%= e.qty %>
        合計金額：
        <%= Product.find(e.product_id).price * e.qty %>円
        <% price = price + Product.find(e.product_id).price * e.qty %>
        <%= link_to '削除', cartitem_path(e), method: :delete %>
    </p>
    </br>
<% end %>
総計金額：<%= price %>
<br>
<%= link_to 'Back', '/' %>
</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |e| %>
    <br>
        <p>
            <%= e.name %>
            <%= e.price %>円
            <%= link_to '削除', product_path(e), method: :delete %>
            <%= link_to 'カートに入れる', new_cartitem_path(product_id: e.id) %>
        </p>
    </br>
<% end %>
<p><%= link_to '新規追加', '/products/new' %></p>
<%= link_to 'カート表示', carts_show_path %>

app/views/products/new.html.erb
<% if @product.errors.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
</ul>
<% end %>



<%= form_for @product , url: {action: :create} do |f| %>
    <%= f.label :name, '商品名' %>
    <%= f.text_field :name %>
    <%= f.label :price, '価格' %>
    <%= f.text_field :price %>
    <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>